package kayit;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class baglanti extends javax.swing.JFrame {

	/**
	 * Creates new form SQL_GUI2
	 */
	public baglanti() {
		initComponents();
		
		tblModel = (DefaultTableModel) jTable1.getModel();
		KDB = new kayitdb(connectionUrl, user, pass);
		tblModel.setColumnIdentifiers(TableColName);
	}
	
	private DefaultTableModel tblModel;
	private String connectionUrl = "jdbc:sqlserver://localhost:1433;databaseName=stokkk;";
	private String user="sa", pass="1122334455";
	String TableColName[] = { "No", "Adi", "Tel" };	// tabloda sütun başlıkları
	private kayitdb KDB; // = new kayitdb(connectionUrl, user, pass);

	private boolean TablodanVeriAl()
	{
		boolean sonuc=false;
		if (tblModel.getRowCount() >= 0 ) {
			int rowIndex = jTable1.getSelectedRow();
			int colIndex = jTable1.getSelectedColumn();

			if (rowIndex>=0 && colIndex>=0)
			{
				Vector row = tblModel.getDataVector().elementAt(rowIndex);
				jtf_Kid.setText(row.elementAt(0).toString());
				jtf_Adi.setText(row.elementAt(1).toString());
				jtf_Tel.setText(row.elementAt(2).toString());
			}
			else
				JOptionPane.showMessageDialog(this,	"Tabloda secim yapilmadi!");
				//	tblModel.getDataVector().elementAt(rowIndex).elementAt(colIndex));	
		}		
		return sonuc;
	}

	private int KayitlariTabloyaYaz()
	{
		int say = 0;
		// clear table rows
		while (tblModel.getRowCount()>0)
			tblModel.removeRow(0);

		ArrayList<Kisi> Kisiler = KDB.KisiListesi(); //new ArrayList<>();
		
		for (Kisi k: Kisiler) {
			String data[] = {String.valueOf(k.getId()), k.getAdi(), k.getTel()};
			tblModel.addRow(data);
			say++;
		}
		
        // Handle any errors that may have occurred.
		return say;
	}

	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jtf_Kid = new javax.swing.JTextField();
        jtf_Adi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtf_Tel = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton_Ekle = new javax.swing.JButton();
        jButton_Listele = new javax.swing.JButton();
        jButton_Gucelle = new javax.swing.JButton();
        jButton_Sil = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Stok ID");

        jLabel2.setText("Stok Adı");

        jLabel3.setText("Stok Adet");

        jButton_Ekle.setText("Yeni Ekle");
        jButton_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EkleActionPerformed(evt);
            }
        });

        jButton_Listele.setText("Listele");
        jButton_Listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListeleActionPerformed(evt);
            }
        });

        jButton_Gucelle.setText("Guncelle");
        jButton_Gucelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GucelleActionPerformed(evt);
            }
        });

        jButton_Sil.setText("Sil");
        jButton_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SilActionPerformed(evt);
            }
        });

        jButton2.setText("Hakkımızda");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("İletişim");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton_Ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton_Gucelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_Listele, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(jButton_Sil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtf_Adi)
                                    .addComponent(jtf_Kid)
                                    .addComponent(jtf_Tel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtf_Kid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_Adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtf_Tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Ekle)
                            .addComponent(jButton_Listele))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Gucelle)
                            .addComponent(jButton_Sil))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_ListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListeleActionPerformed
        KayitlariTabloyaYaz();
    }//GEN-LAST:event_jButton_ListeleActionPerformed

    private void jButton_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EkleActionPerformed
        int k = KDB.KisiEkle(jtf_Kid.getText(), jtf_Adi.getText(), jtf_Tel.getText());
		if (k>0)
		{
			jtf_Kid.setText("");			jtf_Adi.setText("");			jtf_Tel.setText("");
			KayitlariTabloyaYaz();
		}
    }//GEN-LAST:event_jButton_EkleActionPerformed

    private void jButton_GucelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GucelleActionPerformed
        int k = KDB.KisiGuncellle(jtf_Kid.getText(), jtf_Adi.getText(), jtf_Tel.getText());
		if (k>0)
		{
			jtf_Kid.setText("");			jtf_Adi.setText("");			jtf_Tel.setText("");
			KayitlariTabloyaYaz();
		}
    }//GEN-LAST:event_jButton_GucelleActionPerformed

    private void jButton_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SilActionPerformed
        int k = KDB.KisiSil(jtf_Kid.getText(), jtf_Adi.getText(), jtf_Tel.getText());
		if (k>0)
		{
			jtf_Kid.setText("");			jtf_Adi.setText("");			jtf_Tel.setText("");
			KayitlariTabloyaYaz();
		}
    }//GEN-LAST:event_jButton_SilActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
		TablodanVeriAl();
		jTable1.clearSelection();
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Hakkimizda  hak = new Hakkimizda();
            hak.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        iletisim  ilet = new iletisim();
            ilet.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(baglanti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(baglanti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(baglanti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(baglanti.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new baglanti().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton_Ekle;
    private javax.swing.JButton jButton_Gucelle;
    private javax.swing.JButton jButton_Listele;
    private javax.swing.JButton jButton_Sil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtf_Adi;
    private javax.swing.JTextField jtf_Kid;
    private javax.swing.JTextField jtf_Tel;
    // End of variables declaration//GEN-END:variables
}
